# Local Test Configuration (using Z: Mount)
paths:
  rclone_mount: "Z:/PROJETOS/BTC_USDT_L2_2023_2026/btcustd_L2_2026_teste"
  processed_output: "data/L2/pre_processed"
  scaler_path: "data/artifacts/scaler_data.pkl"

etl:
  sampling_interval_ms: 1000
  resampling_interval: "1min"
  orderbook_levels: 200      # Hard Cut 200
  compression: "snappy"
  batch_size_zips: 3         # Process all 3 test zips

features:
  normalization: "log_returns"
  apply_zscore: false
